name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: npm run deploy

      - name: Set up Git
        run: |
          git config --global user.email ${{ secrets.GH_USRMAIL }}
          git config --global user.name ${{ secrets.GH_USR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: fabiojuvenalpereira/fabiojuvenalpereira.github.io
          publish_dir: ./build
