name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./build

    - name: Clone fabiojuvenalpereira.github.io
      run: |
        git clone https://github.com/fabiojuvenalpereira/fabiojuvenalpereira.github.io.git deploy
        cp -r ./build/* deploy/
        cd deploy
        git config --local user.email ${{ secrets.GIT_USER_EMAIL }}
        git config --local user.name ${{ secrets.GIT_USER_NAME }}
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
