name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Clear 'public' directory if it exists and is not empty
      run: |
        if [ -d "public" ] && [ -n "$(ls -A public)" ]; then
          echo "Cleaning 'public' directory..."
          rm -r public/*
        fi

    - name: Copy files to 'public' directory
      run: cp -r build/* public/

    - name: Deploy to GitHub Pages
      run: |
        git clone https://github.com/fabiojuvenalpereira/fabiojuvenalpereira.github.io.git public
        cp -r build/* public/
        cd public
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-deploy from GitHub Actions"
        git push


