on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Clear old files
      run: |
        rm -rf ../fabiojuvenalpereira/fabiojuvenalpereira.github.io/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'build/'
        destination-username: 'fabiojuvenalpereira'
        destination-repository: 'fabiojuvenalpereira.github.io'
        destination-directory: 'public'
        commit-email: 'fabiojuvenalpereira@hotmail.com'

    # - name: Copy build files to GitHub Pages repo
    #   run: |
    #     cp -r build/* ../fabiojuvenalpereira/fabiojuvenalpereira.github.io/
    #     git config --global user.name "GitHub Actions"
    #     git config --global user.email "actions@github.com"
    #     git -C ../fabiojuvenalpereira/fabiojuvenalpereira.github.io/ add .
    #     git -C ../fabiojuvenalpereira/fabiojuvenalpereira.github.io/ commit -m "Atualização automática"
    #     git -C ../fabiojuvenalpereira/fabiojuvenalpereira.github.io/ push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
